### PR TITLE
Fix Issues and new Fan type

### PR DESCRIPTION
**Pull request by joshepw**
Issues solved:

#3 : Added Support to Fan devices
#9 : Added Support to DIY devices
#10 : Fixed update status
#11 : The Air Conditioner is a DIY device, solved

- Media improvements for all device types of media 
- Media play/prev/next support by device type

### CODE REVIEW

**Comment by joshepw** [comment]
Please Test the code first, its my first time with Python 😆

**Comment by KiraPC** [comment]
@joshepw Hello, have you tested this changes? I check the code and seems good.

**Comment by KiraPC** [comment]
@joshepw Do you read me?

**Comment by joshepw** [comment]
Sorry, bussy week, but yes i read you

- Hello, have you tested this changes? I check the code and seems good.
R:// No, i only tested the fix of A/C, i dont have Fans and Lights/Media IRs

**Comment by KiraPC** [comment]
@joshepw ok, let's release as another beta.

**Pull request merged**
